name: "[CI] Precompile"

on:
  push:
    branches:
      - main
  pull_request:

env:
  RUBY_VERSION: 3.0.5
  NODE_VERSION: 16.9.1

jobs:
  lint-report:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Precompile
        run: |
          cd spec/decidim_dummy_app
          bundle exec rails assets:precompile
        env:
          RAILS_ENV: production
          SECRET_KEY_BASE: just-testing