name: "[CI] Unit"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - gemfile: Gemfile.legacy
            ruby_version: 2.7.6
          - gemfile: Gemfile
            ruby_version: 3.0.5

    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true

      - name: Setup Test App
        run: bundle exec rake test_app

      - name: Summary RSpec with config vars disabled
        run: bundle exec rspec spec/awesome_summary_spec.rb
        env:
          FEATURES: disabled
          SIMPLECOV: 1
          CODECOV: 1

      - name: General RSpec with config vars enabled
        run: bundle exec rspec spec/ --exclude-pattern 'spec/system/**/*_spec.rb'
        env:
          FEATURES: enabled
          SIMPLECOV: 1
          CODECOV: 1
